apiVersion: apps/v1
kind: Deployment
metadata:
  name: openmeter-provider-manager
  labels:
    control-plane: openmeter-provider
    app.kubernetes.io/name: openmeter-provider
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    matchLabels:
      control-plane: openmeter-provider
  replicas: 2
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: openmeter-provider
        app.kubernetes.io/name: openmeter-provider
    spec:
      securityContext:
        runAsNonRoot: true
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    control-plane: openmeter-provider
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              control-plane: openmeter-provider
      containers:
      - command:
        - /openmeter-provider
        args:
          - controller-manager
          - --leader-elect
          - --health-probe-bind-address=:8081
          - --server-config=/config/config.yaml
        image: ghcr.io/milo-os/openmeter-provider:dev
        name: manager
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        volumeMounts:
        - name: config
          mountPath: /config
      serviceAccountName: openmeter-provider-manager
      terminationGracePeriodSeconds: 10
      volumes:
      - name: config
        configMap:
          name: openmeter-provider-config
