apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: controller-template-manager
  labels:
    app.kubernetes.io/name: controller-template
    app.kubernetes.io/managed-by: kustomize
spec:
  minAvailable: 1
  selector:
    matchLabels:
      control-plane: controller-template
      app.kubernetes.io/name: controller-template
