apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: openmeter-provider-manager
  labels:
    app.kubernetes.io/name: openmeter-provider
    app.kubernetes.io/managed-by: kustomize
spec:
  minAvailable: 1
  selector:
    matchLabels:
      control-plane: openmeter-provider
      app.kubernetes.io/name: openmeter-provider
