apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - service_account.yaml
  - role.yaml
  - role_binding.yaml

images:
  - name: ghcr.io/milo-os/openmeter-provider
    newTag: latest
