apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openmeter-provider-submission-consumer
rules:
- apiGroups:
  - billing.miloapis.com
  resources:
  - meterdefinitions
  verbs:
  - get
  - list
  - watch
