apiVersion: v1
kind: Service
metadata:
  name: submission-consumer-metrics
  labels:
    control-plane: submission-consumer
    app.kubernetes.io/name: submission-consumer
    app.kubernetes.io/managed-by: kustomize
spec:
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: https
  selector:
    control-plane: submission-consumer
    app.kubernetes.io/name: submission-consumer
