---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openmeter-provider-manager
rules:
- apiGroups:
  - billing.miloapis.com
  resources:
  - meterdefinitions
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - billing.miloapis.com
  resources:
  - meterdefinitions/finalizers
  verbs:
  - update
