apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: controller-template
    app.kubernetes.io/managed-by: kustomize
  name: controller-template-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: controller-template-manager
subjects:
- kind: ServiceAccount
  name: controller-template-manager
  namespace: controller-template-system
