---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openmeter-provider-manager
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - billing.miloapis.com
  resources:
  - billingaccountbindings
  - paymentmethods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - billing.miloapis.com
  resources:
  - billingaccounts
  - meterdefinitions
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - billing.miloapis.com
  resources:
  - billingaccounts/finalizers
  - meterdefinitions/finalizers
  verbs:
  - update
- apiGroups:
  - billing.miloapis.com
  resources:
  - invoices
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - billing.miloapis.com
  resources:
  - invoices/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - stripe.billing.miloapis.com
  resources:
  - stripepaymentmethods
  verbs:
  - get
  - list
  - watch
