apiVersion: apps/v1
kind: Deployment
metadata:
  name: openmeter-provider-manager
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: manager
        image: ghcr.io/milo-os/openmeter-provider:dev
