apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-template-manager
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: manager
        image: ghcr.io/milo-os/controller-template:dev
