namespace: openmeter-system

images:
  - name: ghcr.io/milo-os/openmeter-provider
    newTag: dev

resources:
  - ../../base/manager

components:
  - ../../components/namespace
  - ../../components/controller_rbac
  - ../../components/leader_election

configMapGenerator:
  - name: openmeter-provider-config
    behavior: replace
    files:
      - config.yaml
    options:
      disableNameSuffixHash: true

patches:
  - path: dev_patch.yaml
