apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nats
  namespace: nats-system
  labels:
    app.kubernetes.io/name: nats
    app.kubernetes.io/managed-by: kustomize
spec:
  interval: 1h
  chart:
    spec:
      chart: nats
      version: ">=1.0.0"
      sourceRef:
        kind: HelmRepository
        name: nats-io
        namespace: nats-system
  values:
    config:
      jetstream:
        enabled: true
        fileStore:
          enabled: true
          dir: /data
          maxSize: 10Gi
    podMonitor:
      enabled: true
