// SPDX-License-Identifier: AGPL-3.0-only
// Code generated by defaulter-gen. DO NOT EDIT.

package config

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// RegisterDefaults adds defaulters functions to the given scheme.
// Public to allow building arbitrary schemes and plugins.
func RegisterDefaults(scheme *runtime.Scheme) error {
	scheme.AddTypeDefaultingFunc(&ControllerTemplateOperator{}, func(obj interface{}) {
		SetObjectDefaults_ControllerTemplateOperator(obj.(*ControllerTemplateOperator))
	})
	return nil
}

func SetObjectDefaults_ControllerTemplateOperator(in *ControllerTemplateOperator) {
	SetDefaults_ControllerTemplateOperator(in)
	SetDefaults_MetricsServerConfig(&in.MetricsServer)
	SetDefaults_TLSConfig(&in.MetricsServer.TLS)
	if in.WebhookServer != nil {
		SetDefaults_WebhookServerConfig(in.WebhookServer)
		SetDefaults_TLSConfig(&in.WebhookServer.TLS)
	}
}
