apiVersion: v1
kind: Pod
metadata:
  name: nats-box
  namespace: nats-system
  labels:
    app.kubernetes.io/name: nats-box
    app.kubernetes.io/component: nats-box
    app.kubernetes.io/managed-by: kustomize
spec:
  containers:
    - name: nats-box
      image: natsio/nats-box:0.19.7
      command: ["sleep", "infinity"]
      resources:
        limits:
          cpu: 100m
          memory: 64Mi
        requests:
          cpu: 10m
          memory: 32Mi
